version: '3.8'

services:
    app:
        build:
            context: ./docker/php
        container_name: gatewaypay_api
        volumes:
            - ./:/var/www
        environment:
            - DB_HOST=mysql
            - REDIS_HOST=redis
        depends_on:
            - mysql
            - redis
            - elasticsearch
        networks:
            - gatewaypay_network

    mysql:
        image: mysql:8.0
        container_name: gatewaypay_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gatewaypay
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - gatewaypay_network

    redis:
        image: redis:alpine
        container_name: gatewaypay_redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - gatewaypay_network

    horizon:
        build:
            context: ./docker/php
        container_name: gatewaypay_horizon
        command: php artisan horizon
        volumes:
            - .:/var/www
        depends_on:
            - redis
            - app
        networks:
            - gatewaypay_network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
        container_name: gatewaypay_elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch_data:/usr/share/elasticsearch/data
        networks:
            - gatewaypay_network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.12.0
        container_name: gatewaypay_kibana
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        networks:
            - gatewaypay_network

    nginx:
        container_name: gatewaypay_nginx
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/logs/nginx:/var/log/nginx
        depends_on:
            - app
        ports:
            - "8080:8080"
            - "443:443"
        networks:
            - gatewaypay_network

volumes:
    mysql_data:
    redis_data:
    elasticsearch_data:

networks:
    gatewaypay_network:
        driver: bridge
